### PR TITLE
Added getting started section

### PR DESCRIPTION
**Pull request by dymissy**

### CODE REVIEW

**Comment by lele85** [comment]
Could you provide a webpack section too?

**Comment by ricfrank** [comment]
@lele85 you don't need webpack!!! Settordici is also a module bundler.

**Comment by lele85** [comment]
@ricfrank Thanks. I'm just used to the old ways of doing things... maybe is worth mentioning that in the readme?

**Comment by mazzcris** [comment]
@dymissy merged, thank you for your contribution!

**Pull request merged**
